server:
  port: 8080
spring:
  redis:
    host: 127.0.0.1
    port: 6379
  datasource:
    url: jdbc:h2:mem:test
    driver-class-name: org.h2.Driver
    username: root
    password: 1234
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
    show-sql: true
  mvc:
    path-match:
      matching-strategy: ant_path_matcher
logging:
  config: classpath:logback-spring.xml

mailgun:
  key: mailgunKey